server:
  port: ${AUTH_SERVICE_PORT:8083}
  servlet:
    context-path: /api/auth

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # Cambia a 'update' o 'validate' en producción
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 día en milisegundos
      refresh-token:
        expiration: 604800000 # 7 días en milisegundos

service:
  access:
    url: http://localhost:${ACCESS_SERVICE_PORT:8085}/api/access

logging:
  level:
    org.springframework.security: DEBUG
    com.attention.analysis: DEBUG