spring:
  application:
    name: message-receiver-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update  # Cambiado a update para desarrollo inicial
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_db
    username: postgres
    password: postgres

server:
  port: 8081
  servlet:
    context-path: /api/messages

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    probes:
      enabled: true

aws:
  region: us-east-1
  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/123456789012/whatsapp-message-queue