spring:
  application:
    name: message-receiver-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8081
  servlet:
    context-path: /api/messages

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    probes:
      enabled: true

aws:
  region: us-east-1
  sqs:
    queue-name: whatsapp-message-queue